# Generated by Django 4.2.29 on 2026-04-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='pais',
        ),
    ]
