# Generated by Django 4.2.30 on 2026-06-19 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_registro_cargo_remove_registro_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del turno (ej: Mañana, Tarde, Noche)', max_length=100, validators=[django.core.validators.RegexValidator(code='sql_injection_blocked', message='Caracteres sospechosos no permitidos.', regex='^(?!.*(;|\\-\\-|OR|AND|UNION|SELECT|INSERT|DELETE|UPDATE|DROP|EXEC|EXECUTE|xp_|sp_|0x)).*$')])),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno')),
                ('dias_trabajo', models.CharField(help_text='Días de trabajo (ej: L-M-M-V-F)', max_length=50, validators=[django.core.validators.RegexValidator(code='sql_injection_blocked', message='Caracteres sospechosos no permitidos.', regex='^(?!.*(;|\\-\\-|OR|AND|UNION|SELECT|INSERT|DELETE|UPDATE|DROP|EXEC|EXECUTE|xp_|sp_|0x)).*$')])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['hora_inicio'],
            },
        ),
    ]
