# Generated by Django 4.2.30 on 2026-06-19 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='dias_trabajo',
            field=models.CharField(help_text='Días de trabajo (ej: L-M-M-V-F)', max_length=50, validators=[django.core.validators.RegexValidator(code='sql_injection_blocked', message='Caracteres sospechosos no permitidos.', regex='^(?!.*(?:;|\\-\\-|OR|AND|UNION|SELECT|INSERT|DELETE|UPDATE|DROP|EXEC|EXECUTE|xp_|sp_|0x)).*$')]),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='nombre',
            field=models.CharField(help_text='Nombre del turno (ej: Mañana, Tarde, Noche)', max_length=100, validators=[django.core.validators.RegexValidator(code='sql_injection_blocked', message='Caracteres sospechosos no permitidos.', regex='^(?!.*(?:;|\\-\\-|OR|AND|UNION|SELECT|INSERT|DELETE|UPDATE|DROP|EXEC|EXECUTE|xp_|sp_|0x)).*$')]),
        ),
    ]
