# Generated by Django 4.2.30 on 2026-06-22 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_alter_jornada_dias_trabajo_alter_jornada_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='barrio',
            field=models.CharField(blank=True, help_text='Barrio asociado a la jornada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='barrio',
            field=models.CharField(blank=True, help_text='Barrio de residencia', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.BooleanField(default=False, help_text='Indica si el residente asistió a la jornada')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='website.jornada')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('residente', 'jornada')},
            },
        ),
    ]
